### PR TITLE
implement with ES6 classes

### PR DESCRIPTION
**Pull request by staltz**
Changes the implementation of all operators to use ES6 classes instead of "prototype function classes".

Also:
- imports are always at the top
- exports are always at the bottom

Doesn't touch tests files.

### CODE REVIEW

**Comment by arj03** [comment]
I like that this uses a standard way to inheritance etc. What I'm a little concerned with is that the benchmark for: pull.values now seems to be around 30-40% lower than [master](https://github.com/push-stream/push-stream/pull/13#issuecomment-1307008551).

**Comment by staltz** [comment]
CI is drunk (why though??), here are how the numbers look locally for me:

```
-------
Benchmarking
pull.values x 99 ops/sec @ 10ms/op ± 1.89% (min: 6ms, max: 29ms)
push.values x 652 ops/sec @ 1ms/op ± 1.90% (min: 1ms, max: 6ms)
pull.asyncMap x 45 ops/sec @ 22ms/op ± 1.15% (min: 16ms, max: 46ms)
push.asyncMap x 108 ops/sec @ 9ms/op ± 1.48% (min: 7ms, max: 28ms)
pull.filter x 30 ops/sec @ 33ms/op
push.filter x 36 ops/sec @ 27ms/op
-------
Benchmarking
RAM: rss=40.0mb heap=10.8mb used=5.4mb ext=0.9mb
pull.collect x 41 ops/sec @ 23ms/op
RAM: rss=103.5mb heap=71.0mb used=42.6mb ext=0.9mb
-------
Benchmarking
RAM: rss=40.0mb heap=11.0mb used=5.3mb ext=0.9mb
push.collect x 128 ops/sec @ 7ms/op ± 1.28% (min: 5ms, max: 20ms)
RAM: rss=66.9mb heap=64.8mb used=29.9mb ext=0.9mb
```

**Comment by arj03** [comment]
And how is that compared to master?

**Comment by staltz** [comment]
Approx the same:

```
-------
Benchmarking
pull.values x 130 ops/sec @ 7ms/op ± 1.29% (min: 6ms, max: 19ms)
push.values x 674 ops/sec @ 1ms/op ± 1.39% (min: 1ms, max: 6ms)
pull.asyncMap x 44 ops/sec @ 22ms/op ± 1.51% (min: 16ms, max: 53ms)
push.asyncMap x 100 ops/sec @ 9ms/op ± 1.73% (min: 7ms, max: 35ms)
pull.filter x 29 ops/sec @ 33ms/op
push.filter x 35 ops/sec @ 28ms/op
-------
Benchmarking
RAM: rss=39.8mb heap=11.0mb used=5.4mb ext=0.9mb
pull.collect x 42 ops/sec @ 23ms/op
RAM: rss=79.8mb heap=47.2mb used=17.0mb ext=0.9mb
-------
Benchmarking
RAM: rss=40.0mb heap=10.8mb used=5.3mb ext=0.9mb
push.collect x 118 ops/sec @ 8ms/op ± 1.72% (min: 5ms, max: 21ms)
RAM: rss=75.3mb heap=72.8mb used=38.1mb ext=0.9mb
```

**Review by arj03 — APPROVED** [review]
Great 👍

**Pull request merged**
